version: '3.6'
services:

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
      - '50022:50022'
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
         - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
    restart: always
    user: root


  smee:
   image: deltaprojects/smee-client
   container_name: smee
   ports:
       - '3000:3000'
   command: ["--url","https://smee.io/Ozitw69Ekyv6Bh2","--target", "http://jenkins:8080/jenkins/github-webhook/"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./certs/:/etc/nginx/ssl/ # uncomment for SSL certificates
      - ./staticfiles/javadoc/:/var/staticfiles/javadoc
    restart: always



volumes:
  jenkins-data:
